#!/bin/bash
#
# An example hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.
#
# To enable this hook, rename this file to "prepare-commit-msg".

# This hook includes three examples.  The first comments out the
# "Conflicts:" part of a merge commit.
#
# The second includes the output of "git diff --name-status -r"
# into the message, just before the "git status" output.  It is
# commented because it doesn't cope with --amend or with squashed
# commits.
#
# The third example adds a Signed-off-by line to the message, that can
# still be edited.  This is rarely a good idea.

#case "$2,$3" in
#  merge,)
#    /usr/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;

# ,|template,)
#   /usr/bin/perl -i.bak -pe '
#      print "\n" . `git diff --cached --name-status -r`
#	 if /^#/ && $first++ == 0' "$1" ;;

#  *) ;;
#esac

# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

ORIGINAL_MSG=$(cat $1)
BRANCH_NAME=$(git symbolic-ref --short HEAD)
regex="[issue]/([0-9]+.*)"
if [[ $BRANCH_NAME =~ $regex ]]
then
  ISSUE_NO="${BASH_REMATCH[1]}"
  echo "ISSUE-$ISSUE_NO: $ORIGINAL_MSG" > $1
elif [[ -z $BRANCH_NAME ]]
then
  echo "empty branch name, probably in the middle of rebasing, ignoring"
  echo "$ORIGINAL_MSG" > $1
else
  echo "branch name must follow pattern: regex=$regex, branch name=$BRANCH_NAME"
  exit 1
fi
