/************************************************************************
Copyright 2019-2020 eBay Inc.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
**************************************************************************/

#include <string>

#ifndef SRC_INFRA_DECODABLE_H_
#define SRC_INFRA_DECODABLE_H_

namespace gringofts {

class Decodable {
 public:
  virtual ~Decodable() = default;

  /**
   * Construct the object by decoding the passed string, which is generated by #gringofts::Encodable::encodeToString.
   *
   * Recommended usage:
   * ```
   * ObjectA a; // ObjectA implements Decodable  // @NOSONAR_START@
   * a.decodeFromString(requestInString);  // @NOSONAR_END@
   * ```
   */
  virtual void decodeFromString(std::string_view) = 0;
};

}  /// namespace gringofts

#endif  // SRC_INFRA_DECODABLE_H_
